on:
  pull_request_review:
    types: [submitted]

jobs:
  process:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check maintainer
        run: grep -x "${{ github.event.review.user.login }}" maintainers.txt || exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: process submission
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: bash process.sh
